START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN

    DO $$
    DECLARE bad_loans int; bad_hist int;
    BEGIN
      SELECT count(*) INTO bad_loans FROM "Loans"
       WHERE "Status" NOT IN ('Draft', 'Submitted', 'UnderReview', 'Approved', 'Rejected', 'Disbursed', 'Closed', 'OnHold', 'Decision', 'Acceptance', 'Offer')
          OR ("PreRejectedStatus" IS NOT NULL AND "PreRejectedStatus" NOT IN ('Draft', 'Submitted', 'UnderReview', 'Approved', 'Rejected', 'Disbursed', 'Closed', 'OnHold', 'Decision', 'Acceptance', 'Offer'));
      SELECT count(*) INTO bad_hist FROM "LoanStatusHistories"
       WHERE "FromStatus" NOT IN ('Draft', 'Submitted', 'UnderReview', 'Approved', 'Rejected', 'Disbursed', 'Closed', 'OnHold', 'Decision', 'Acceptance', 'Offer') OR "ToStatus" NOT IN ('Draft', 'Submitted', 'UnderReview', 'Approved', 'Rejected', 'Disbursed', 'Closed', 'OnHold', 'Decision', 'Acceptance', 'Offer');
      IF bad_loans > 0 OR bad_hist > 0 THEN
        RAISE EXCEPTION 'NI/Cancelled removal: % loan row(s) and % status-history row(s) carry a status outside LoanStatus (e.g. NI / Cancelled). Resolve them from the backup before migrating.', bad_loans, bad_hist;
      END IF;
    END $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE TABLE "ApplicationOffers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "BankId" integer NOT NULL,
        "LenderName" character varying(200) NOT NULL,
        "ProductKey" character varying(100) NOT NULL,
        "LoanType" character varying(50) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "DeviationStatus" character varying(20) NOT NULL,
        "ApprovalStatus" character varying(20) NOT NULL,
        "CurrentRevisionNo" integer NOT NULL,
        "ValidUntil" timestamp with time zone,
        "Version" integer NOT NULL,
        "SelectedAt" timestamp with time zone,
        "SelectedByUserId" integer,
        "SelectedRevisionNo" integer,
        "StatusReason" character varying(1000),
        "CreatedByUserId" integer NOT NULL,
        "UpdatedByUserId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_ApplicationOffers" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ApplicationOffers_ApprovalStatus" CHECK ("ApprovalStatus" IN ('Pending', 'Approved', 'Rejected')),
        CONSTRAINT "CK_ApplicationOffers_DeviationStatus" CHECK ("DeviationStatus" IN ('NotRequired', 'Required', 'Raised', 'Approved', 'Rejected', 'Skipped')),
        CONSTRAINT "CK_ApplicationOffers_FinalSelection" CHECK ("Status" <> 'Final' OR ("SelectedAt" IS NOT NULL AND "SelectedRevisionNo" IS NOT NULL)),
        CONSTRAINT "CK_ApplicationOffers_Status" CHECK ("Status" IN ('Available', 'Final', 'NotSelected', 'Withdrawn', 'Expired')),
        CONSTRAINT "FK_ApplicationOffers_Banks_BankId" FOREIGN KEY ("BankId") REFERENCES "Banks" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ApplicationOffers_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ApplicationOffers_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE TABLE "DeviationRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RuleKey" character varying(64) NOT NULL,
        "Version" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "BankId" integer NOT NULL,
        "ProductKey" character varying(100),
        "LoanType" character varying(50),
        "DeviationType" character varying(30) NOT NULL,
        "Metric" character varying(40) NOT NULL,
        "LimitValue" numeric(18,2) NOT NULL,
        "MaxApprovableDeviation" numeric(18,2),
        "ConditionsJson" text NOT NULL,
        "ConditionLogic" character varying(3) NOT NULL,
        "Priority" integer NOT NULL,
        "EffectiveFrom" timestamp with time zone NOT NULL,
        "EffectiveTo" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "ApprovalRequired" boolean NOT NULL,
        "Notes" character varying(1000),
        "CreatedByUserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "SupersededAt" timestamp with time zone,
        "DeactivatedAt" timestamp with time zone,
        "DeactivatedByUserId" integer,
        CONSTRAINT "PK_DeviationRules" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_DeviationRules_Dates" CHECK ("EffectiveTo" IS NULL OR "EffectiveTo" >= "EffectiveFrom"),
        CONSTRAINT "CK_DeviationRules_Logic" CHECK ("ConditionLogic" IN ('AND', 'OR')),
        CONSTRAINT "FK_DeviationRules_Banks_BankId" FOREIGN KEY ("BankId") REFERENCES "Banks" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE TABLE "ApplicationOfferRevisions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OfferId" integer NOT NULL,
        "RevisionNo" integer NOT NULL,
        "LoanAmount" numeric(18,2) NOT NULL,
        "TenureMonths" integer NOT NULL,
        "BaseRoi" numeric(5,2) NOT NULL,
        "OfferedRoi" numeric(5,2) NOT NULL,
        "RateType" character varying(20) NOT NULL,
        "ProcessingFeePct" numeric(5,2) NOT NULL,
        "ProcessingFeeAmount" numeric(18,2) NOT NULL,
        "GstPct" numeric(5,2) NOT NULL,
        "GstAmount" numeric(18,2) NOT NULL,
        "InsuranceAmount" numeric(18,2) NOT NULL,
        "PfInBundled" boolean NOT NULL,
        "InsuranceInBundled" boolean NOT NULL,
        "BtAmount" numeric(18,2) NOT NULL,
        "StampDuty" numeric(18,2) NOT NULL,
        "FinancedPrincipal" numeric(18,2) NOT NULL,
        "Emi" numeric(18,2) NOT NULL,
        "NetDisbursement" numeric(18,2) NOT NULL,
        "ChangeReason" character varying(1000),
        "EvaluationJson" text,
        "EvaluationOutcome" character varying(20) NOT NULL,
        "CreatedByUserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ApplicationOfferRevisions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_OfferRevisions_Positive" CHECK ("LoanAmount" > 0 AND "TenureMonths" > 0 AND "OfferedRoi" >= 0 AND "NetDisbursement" > 0),
        CONSTRAINT "FK_ApplicationOfferRevisions_ApplicationOffers_OfferId" FOREIGN KEY ("OfferId") REFERENCES "ApplicationOffers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE TABLE "CreditApprovals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "OfferId" integer NOT NULL,
        "RevisionNo" integer NOT NULL,
        "BankId" integer NOT NULL,
        "LenderName" character varying(200) NOT NULL,
        "Decision" character varying(20) NOT NULL,
        "Comment" character varying(2000),
        "TermsSnapshotJson" text NOT NULL,
        "DeviationRefsJson" text,
        "DeviationStatusAtApproval" character varying(20) NOT NULL,
        "ApproverUserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsCurrent" boolean NOT NULL,
        "IdempotencyKey" character varying(100),
        CONSTRAINT "PK_CreditApprovals" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_CreditApprovals_Decision" CHECK ("Decision" IN ('Approved', 'Rejected')),
        CONSTRAINT "FK_CreditApprovals_ApplicationOffers_OfferId" FOREIGN KEY ("OfferId") REFERENCES "ApplicationOffers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_CreditApprovals_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_CreditApprovals_Users_ApproverUserId" FOREIGN KEY ("ApproverUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE TABLE "OfferDeviations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "OfferId" integer NOT NULL,
        "RevisionNo" integer NOT NULL,
        "BankId" integer NOT NULL,
        "DeviationType" character varying(40) NOT NULL,
        "Source" character varying(10) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "Reason" character varying(2000) NOT NULL,
        "RuleSnapshotJson" text,
        "OfferSnapshotJson" text,
        "RaisedByUserId" integer NOT NULL,
        "RaisedAt" timestamp with time zone NOT NULL,
        "AssignedApproverId" integer,
        "AssignmentState" character varying(20) NOT NULL,
        "DecidedByUserId" integer,
        "DecidedAt" timestamp with time zone,
        "DecisionComment" character varying(2000),
        "ClosedReason" character varying(500),
        "IdempotencyKey" character varying(100),
        "DecisionIdempotencyKey" character varying(100),
        "TaskId" integer,
        CONSTRAINT "PK_OfferDeviations" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_OfferDeviations_NoSelfApproval" CHECK ("Status" <> 'Approved' OR "DecidedByUserId" <> "RaisedByUserId"),
        CONSTRAINT "CK_OfferDeviations_Status" CHECK ("Status" IN ('Raised', 'Approved', 'Rejected', 'Skipped', 'Closed')),
        CONSTRAINT "FK_OfferDeviations_ApplicationOffers_OfferId" FOREIGN KEY ("OfferId") REFERENCES "ApplicationOffers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_OfferDeviations_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_OfferDeviations_Users_RaisedByUserId" FOREIGN KEY ("RaisedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE TABLE "Sanctions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "SanctionNumber" character varying(60) NOT NULL,
        "SanctionVersion" integer NOT NULL,
        "PreviousSanctionId" integer,
        "OfferId" integer NOT NULL,
        "RevisionNo" integer NOT NULL,
        "CreditApprovalId" integer NOT NULL,
        "BankId" integer NOT NULL,
        "LenderName" character varying(200) NOT NULL,
        "LoanAmount" numeric(18,2) NOT NULL,
        "TenureMonths" integer NOT NULL,
        "Roi" numeric(5,2) NOT NULL,
        "Emi" numeric(18,2) NOT NULL,
        "ProcessingFeePct" numeric(5,2) NOT NULL,
        "ProcessingFeeAmount" numeric(18,2) NOT NULL,
        "GstPct" numeric(5,2) NOT NULL,
        "GstAmount" numeric(18,2) NOT NULL,
        "InsuranceAmount" numeric(18,2) NOT NULL,
        "BtAmount" numeric(18,2) NOT NULL,
        "StampDuty" numeric(18,2) NOT NULL,
        "FinancedPrincipal" numeric(18,2) NOT NULL,
        "NetDisbursement" numeric(18,2) NOT NULL,
        "DeviationRefsJson" text,
        "Status" character varying(20) NOT NULL,
        "GeneratedByUserId" integer NOT NULL,
        "GeneratedAt" timestamp with time zone NOT NULL,
        "CancellationType" character varying(20),
        "CancelReason" character varying(1000),
        "CancelledByUserId" integer,
        "CancelledAt" timestamp with time zone,
        "IdempotencyKey" character varying(100),
        CONSTRAINT "PK_Sanctions" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Sanctions_CancelReason" CHECK ("Status" <> 'Cancelled' OR ("CancelReason" IS NOT NULL AND "CancelledAt" IS NOT NULL)),
        CONSTRAINT "CK_Sanctions_Status" CHECK ("Status" IN ('Active', 'Cancelled')),
        CONSTRAINT "FK_Sanctions_ApplicationOffers_OfferId" FOREIGN KEY ("OfferId") REFERENCES "ApplicationOffers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Sanctions_CreditApprovals_CreditApprovalId" FOREIGN KEY ("CreditApprovalId") REFERENCES "CreditApprovals" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Sanctions_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Sanctions_Sanctions_PreviousSanctionId" FOREIGN KEY ("PreviousSanctionId") REFERENCES "Sanctions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE TABLE "Disbursements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "SanctionId" integer NOT NULL,
        "Type" character varying(20) NOT NULL,
        "ReversalOfId" integer,
        "Amount" numeric(18,2) NOT NULL,
        "DisbursementDate" timestamp with time zone NOT NULL,
        "BankAccountNumber" character varying(34) NOT NULL,
        "Ifsc" character varying(11) NOT NULL,
        "AccountHolderName" character varying(200),
        "Utr" character varying(50) NOT NULL,
        "LenderReference" character varying(100),
        "Mode" character varying(20) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "Reason" character varying(1000),
        "PreviousLoanStatus" character varying(20),
        "CreatedByUserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IdempotencyKey" character varying(100),
        CONSTRAINT "PK_Disbursements" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Disbursements_Amount" CHECK ("Amount" > 0),
        CONSTRAINT "CK_Disbursements_ReversalRef" CHECK ("Type" <> 'Reversal' OR ("ReversalOfId" IS NOT NULL AND "Reason" IS NOT NULL)),
        CONSTRAINT "CK_Disbursements_Status" CHECK ("Status" IN ('Completed', 'Reversed')),
        CONSTRAINT "CK_Disbursements_Type" CHECK ("Type" IN ('Disbursement', 'Reversal')),
        CONSTRAINT "FK_Disbursements_Disbursements_ReversalOfId" FOREIGN KEY ("ReversalOfId") REFERENCES "Disbursements" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Disbursements_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Disbursements_Sanctions_SanctionId" FOREIGN KEY ("SanctionId") REFERENCES "Sanctions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    ALTER TABLE "LoanStatusHistories" ADD CONSTRAINT "CK_LoanStatusHistories_FromStatus" CHECK ("FromStatus" IN ('Draft', 'Submitted', 'UnderReview', 'Approved', 'Rejected', 'Disbursed', 'Closed', 'OnHold', 'Decision', 'Acceptance', 'Offer'));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    ALTER TABLE "LoanStatusHistories" ADD CONSTRAINT "CK_LoanStatusHistories_ToStatus" CHECK ("ToStatus" IN ('Draft', 'Submitted', 'UnderReview', 'Approved', 'Rejected', 'Disbursed', 'Closed', 'OnHold', 'Decision', 'Acceptance', 'Offer'));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    ALTER TABLE "Loans" ADD CONSTRAINT "CK_Loans_PreRejectedStatus" CHECK ("PreRejectedStatus" IS NULL OR "PreRejectedStatus" IN ('Draft', 'Submitted', 'UnderReview', 'Approved', 'Rejected', 'Disbursed', 'Closed', 'OnHold', 'Decision', 'Acceptance', 'Offer'));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    ALTER TABLE "Loans" ADD CONSTRAINT "CK_Loans_Status" CHECK ("Status" IN ('Draft', 'Submitted', 'UnderReview', 'Approved', 'Rejected', 'Disbursed', 'Closed', 'OnHold', 'Decision', 'Acceptance', 'Offer'));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "IX_ApplicationOfferRevisions_OfferId_RevisionNo" ON "ApplicationOfferRevisions" ("OfferId", "RevisionNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_ApplicationOffers_BankId" ON "ApplicationOffers" ("BankId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_ApplicationOffers_CreatedByUserId" ON "ApplicationOffers" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_ApplicationOffers_LoanId" ON "ApplicationOffers" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "UX_ApplicationOffers_Loan_Bank_Active" ON "ApplicationOffers" ("LoanId", "BankId") WHERE "IsDeleted" = false AND "Status" IN ('Available', 'Final');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "UX_ApplicationOffers_Loan_Final" ON "ApplicationOffers" ("LoanId") WHERE "IsDeleted" = false AND "Status" = 'Final';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_CreditApprovals_ApproverUserId" ON "CreditApprovals" ("ApproverUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "IX_CreditApprovals_IdempotencyKey" ON "CreditApprovals" ("IdempotencyKey") WHERE "IdempotencyKey" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_CreditApprovals_LoanId" ON "CreditApprovals" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_CreditApprovals_OfferId" ON "CreditApprovals" ("OfferId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_DeviationRules_BankId_DeviationType" ON "DeviationRules" ("BankId", "DeviationType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "IX_DeviationRules_RuleKey_Version" ON "DeviationRules" ("RuleKey", "Version");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "IX_Disbursements_IdempotencyKey" ON "Disbursements" ("IdempotencyKey") WHERE "IdempotencyKey" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_Disbursements_ReversalOfId" ON "Disbursements" ("ReversalOfId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_Disbursements_SanctionId" ON "Disbursements" ("SanctionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "UX_Disbursements_Loan_Completed" ON "Disbursements" ("LoanId") WHERE "Type" = 'Disbursement' AND "Status" = 'Completed';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "IX_OfferDeviations_DecisionIdempotencyKey" ON "OfferDeviations" ("DecisionIdempotencyKey") WHERE "DecisionIdempotencyKey" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "IX_OfferDeviations_IdempotencyKey" ON "OfferDeviations" ("IdempotencyKey") WHERE "IdempotencyKey" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_OfferDeviations_LoanId" ON "OfferDeviations" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_OfferDeviations_RaisedByUserId" ON "OfferDeviations" ("RaisedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "UX_OfferDeviations_Offer_Raised" ON "OfferDeviations" ("OfferId") WHERE "Status" = 'Raised';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_Sanctions_CreditApprovalId" ON "Sanctions" ("CreditApprovalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "IX_Sanctions_IdempotencyKey" ON "Sanctions" ("IdempotencyKey") WHERE "IdempotencyKey" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_Sanctions_OfferId" ON "Sanctions" ("OfferId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE INDEX "IX_Sanctions_PreviousSanctionId" ON "Sanctions" ("PreviousSanctionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "IX_Sanctions_SanctionNumber" ON "Sanctions" ("SanctionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    CREATE UNIQUE INDEX "UX_Sanctions_Loan_Active" ON "Sanctions" ("LoanId") WHERE "Status" = 'Active';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN

    CREATE OR REPLACE FUNCTION loanms_offer_max_active() RETURNS trigger AS $$
    DECLARE n int;
    BEGIN
      IF NEW."IsDeleted" = false AND NEW."Status" IN ('Available','Final') THEN
        PERFORM 1 FROM "Loans" WHERE "Id" = NEW."LoanId" FOR UPDATE;
        SELECT count(*) INTO n FROM "ApplicationOffers"
         WHERE "LoanId" = NEW."LoanId" AND "Id" <> NEW."Id" AND "IsDeleted" = false
           AND "Status" IN ('Available','Final');
        IF n >= 3 THEN
          RAISE EXCEPTION 'An application can hold at most 3 active lender offers.' USING ERRCODE = 'P0001';
        END IF;
      END IF;
      IF TG_OP = 'UPDATE' THEN
        IF NEW."LoanId" <> OLD."LoanId" OR NEW."BankId" <> OLD."BankId" THEN
          RAISE EXCEPTION 'An offer''s application and lender cannot change.' USING ERRCODE = 'P0001';
        END IF;
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    CREATE TRIGGER trg_offer_max_active BEFORE INSERT OR UPDATE ON "ApplicationOffers"
      FOR EACH ROW EXECUTE FUNCTION loanms_offer_max_active();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN

    CREATE OR REPLACE FUNCTION loanms_immutable_row() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION '% rows are immutable (% refused).', TG_TABLE_NAME, TG_OP USING ERRCODE = 'P0001';
    END $$ LANGUAGE plpgsql;
    CREATE TRIGGER trg_offer_revision_immutable BEFORE UPDATE OR DELETE ON "ApplicationOfferRevisions"
      FOR EACH ROW EXECUTE FUNCTION loanms_immutable_row();
    CREATE TRIGGER trg_offer_no_delete BEFORE DELETE ON "ApplicationOffers"
      FOR EACH ROW EXECUTE FUNCTION loanms_immutable_row();
    CREATE TRIGGER trg_credit_approval_no_delete BEFORE DELETE ON "CreditApprovals"
      FOR EACH ROW EXECUTE FUNCTION loanms_immutable_row();
    CREATE TRIGGER trg_sanction_no_delete BEFORE DELETE ON "Sanctions"
      FOR EACH ROW EXECUTE FUNCTION loanms_immutable_row();
    CREATE TRIGGER trg_disbursement_no_delete BEFORE DELETE ON "Disbursements"
      FOR EACH ROW EXECUTE FUNCTION loanms_immutable_row();
    CREATE TRIGGER trg_deviation_rule_no_delete BEFORE DELETE ON "DeviationRules"
      FOR EACH ROW EXECUTE FUNCTION loanms_immutable_row();
    CREATE TRIGGER trg_offer_deviation_no_delete BEFORE DELETE ON "OfferDeviations"
      FOR EACH ROW EXECUTE FUNCTION loanms_immutable_row();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN

    CREATE OR REPLACE FUNCTION loanms_credit_approval_guard() RETURNS trigger AS $$
    BEGIN
      IF (to_jsonb(NEW) - 'IsCurrent') IS DISTINCT FROM (to_jsonb(OLD) - 'IsCurrent')
         OR (OLD."IsCurrent" = false AND NEW."IsCurrent" = true) THEN
        RAISE EXCEPTION 'Credit approvals are immutable (only invalidation is allowed).' USING ERRCODE = 'P0001';
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    CREATE TRIGGER trg_credit_approval_guard BEFORE UPDATE ON "CreditApprovals"
      FOR EACH ROW EXECUTE FUNCTION loanms_credit_approval_guard();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN

    CREATE OR REPLACE FUNCTION loanms_sanction_guard() RETURNS trigger AS $$
    BEGIN
      IF (to_jsonb(NEW) - ARRAY['Status','CancellationType','CancelReason','CancelledByUserId','CancelledAt'])
         IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['Status','CancellationType','CancelReason','CancelledByUserId','CancelledAt']) THEN
        RAISE EXCEPTION 'Sanction terms are immutable — cancel with type Amendment and re-sanction.' USING ERRCODE = 'P0001';
      END IF;
      IF OLD."Status" <> 'Active' THEN
        RAISE EXCEPTION 'A % sanction cannot be changed.', OLD."Status" USING ERRCODE = 'P0001';
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    CREATE TRIGGER trg_sanction_guard BEFORE UPDATE ON "Sanctions"
      FOR EACH ROW EXECUTE FUNCTION loanms_sanction_guard();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN

    CREATE OR REPLACE FUNCTION loanms_disbursement_guard() RETURNS trigger AS $$
    BEGIN
      IF (to_jsonb(NEW) - 'Status') IS DISTINCT FROM (to_jsonb(OLD) - 'Status')
         OR NOT (OLD."Status" = 'Completed' AND NEW."Status" IN ('Completed','Reversed')) THEN
        RAISE EXCEPTION 'Disbursement records are immutable — post a reversal instead.' USING ERRCODE = 'P0001';
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    CREATE TRIGGER trg_disbursement_guard BEFORE UPDATE ON "Disbursements"
      FOR EACH ROW EXECUTE FUNCTION loanms_disbursement_guard();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN

    CREATE OR REPLACE FUNCTION loanms_rule_version_guard() RETURNS trigger AS $$
    BEGIN
      IF (to_jsonb(NEW) - ARRAY['IsActive','SupersededAt','DeactivatedAt','DeactivatedByUserId'])
         IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['IsActive','SupersededAt','DeactivatedAt','DeactivatedByUserId']) THEN
        RAISE EXCEPTION 'A deviation rule version is immutable — create a new version.' USING ERRCODE = 'P0001';
      END IF;
      IF OLD."SupersededAt" IS NOT NULL AND NEW."IsActive" = true THEN
        RAISE EXCEPTION 'A superseded rule version cannot be re-activated.' USING ERRCODE = 'P0001';
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    CREATE TRIGGER trg_rule_version_guard BEFORE UPDATE ON "DeviationRules"
      FOR EACH ROW EXECUTE FUNCTION loanms_rule_version_guard();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN

    CREATE OR REPLACE FUNCTION loanms_offer_deviation_guard() RETURNS trigger AS $$
    BEGIN
      IF OLD."Status" <> 'Raised' AND (to_jsonb(NEW) - 'TaskId') IS DISTINCT FROM (to_jsonb(OLD) - 'TaskId') THEN
        RAISE EXCEPTION 'A % deviation request is final — raise a new request on revised terms.', OLD."Status" USING ERRCODE = 'P0001';
      END IF;
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    CREATE TRIGGER trg_offer_deviation_guard BEFORE UPDATE ON "OfferDeviations"
      FOR EACH ROW EXECUTE FUNCTION loanms_offer_deviation_guard();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925041918_AddOfferWorkflowAndStatusChecks') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260925041918_AddOfferWorkflowAndStatusChecks', '10.0.0');
    END IF;
END $EF$;
COMMIT;

