CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityName" character varying(100) NOT NULL,
        "Action" character varying(50) NOT NULL,
        "EntityId" text,
        "OldValues" text,
        "NewValues" text,
        "UserId" integer,
        "UserName" text,
        "IpAddress" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "Locations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "City" text NOT NULL,
        "State" text NOT NULL,
        "PinCode" text,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Locations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(150) NOT NULL,
        "Email" character varying(200) NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "RefreshToken" text,
        "RefreshTokenExpiry" timestamp with time zone,
        "MustChangePassword" boolean NOT NULL,
        "FailedLoginAttempts" integer NOT NULL,
        "LockedUntil" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "Customers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(150) NOT NULL,
        "Email" character varying(200) NOT NULL,
        "Phone" character varying(15) NOT NULL,
        "PanNumber" character varying(10),
        "AadhaarNumber" character varying(12),
        "DateOfBirth" timestamp with time zone,
        "Address" text,
        "City" text,
        "State" text,
        "PinCode" text,
        "MonthlyIncome" decimal(18,2),
        "EmploymentType" text,
        "CompanyName" text,
        "CibilScore" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "AppSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Key" character varying(100) NOT NULL,
        "Value" text NOT NULL,
        "Category" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_AppSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "PayoutRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanType" character varying(50) NOT NULL,
        "Percentage" decimal(5,2) NOT NULL,
        "MinPayout" decimal(18,2),
        "MaxPayout" decimal(18,2),
        "IsActive" boolean NOT NULL,
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PayoutRules" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "DsaPartners" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(150) NOT NULL,
        "Code" character varying(20) NOT NULL,
        "Email" text,
        "Phone" text,
        "City" text,
        "IsActive" boolean NOT NULL,
        "MappedSalesUserId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_DsaPartners" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DsaPartners_Users_MappedSalesUserId" FOREIGN KEY ("MappedSalesUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "PasswordResetTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TokenHash" character varying(64) NOT NULL,
        "UserId" integer NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsUsed" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "Teams" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Type" text NOT NULL,
        "LocationId" integer,
        "TeamLeadUserId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Teams" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Teams_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Teams_Users_TeamLeadUserId" FOREIGN KEY ("TeamLeadUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "Loans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanNumber" character varying(20) NOT NULL,
        "LoanType" text NOT NULL,
        "Status" text NOT NULL,
        "RequestedAmount" decimal(18,2) NOT NULL,
        "ApprovedAmount" decimal(18,2),
        "InterestRate" decimal(5,2) NOT NULL,
        "TenureMonths" integer NOT NULL,
        "MonthlyEmi" decimal(18,2),
        "Purpose" text,
        "Remarks" text,
        "ApprovedAt" timestamp with time zone,
        "DisbursedAt" timestamp with time zone,
        "ClosedAt" timestamp with time zone,
        "CustomerId" integer NOT NULL,
        "CreatedByUserId" integer NOT NULL,
        "AssignedToUserId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Loans" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Loans_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Loans_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Loans_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "LoanDocuments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "DocumentName" text NOT NULL,
        "DocumentType" text NOT NULL,
        "FilePath" text NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "UploadedByUserId" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_LoanDocuments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanDocuments_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "LoanStatusHistories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "FromStatus" text NOT NULL,
        "ToStatus" text NOT NULL,
        "Comment" text,
        "ChangedByUserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_LoanStatusHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanStatusHistories_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LoanStatusHistories_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "TrackingEntries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "Name" text NOT NULL,
        "Stage" text NOT NULL,
        "AssignedUser" text NOT NULL,
        "Status" text NOT NULL,
        "Comment" text,
        "SubNote" text,
        "CreatedByUserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_TrackingEntries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TrackingEntries_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TrackingEntries_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "Tasks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer,
        "Title" text NOT NULL,
        "Description" text,
        "Priority" text NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "DueDate" timestamp with time zone,
        "AssignedToUserId" integer NOT NULL,
        "CreatedByUserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tasks_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tasks_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Tasks_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "Tickets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Status" text NOT NULL,
        "Priority" text NOT NULL,
        "LoanId" integer,
        "CreatedByUserId" integer NOT NULL,
        "AssignedToUserId" integer,
        "ClosedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tickets_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Tickets_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Tickets_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "PayoutClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "ClaimedByUserId" integer NOT NULL,
        "ClaimAmount" decimal(18,2) NOT NULL,
        "Status" text NOT NULL,
        "Month" text,
        "Notes" text,
        "VerifiedAt" timestamp with time zone,
        "PaidAt" timestamp with time zone,
        "ProcessedByUserId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PayoutClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PayoutClaims_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PayoutClaims_Users_ClaimedByUserId" FOREIGN KEY ("ClaimedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PayoutClaims_Users_ProcessedByUserId" FOREIGN KEY ("ProcessedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "LoanReferences" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "Name" character varying(150) NOT NULL,
        "Mobile" character varying(15) NOT NULL,
        "Relation" character varying(50) NOT NULL,
        "RefNumber" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_LoanReferences" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanReferences_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE TABLE "TeamMembers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TeamId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_TeamMembers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TeamMembers_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TeamMembers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_CreatedAt" ON "AuditLogs" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_EntityName" ON "AuditLogs" ("EntityName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Customers_Email" ON "Customers" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Customers_PanNumber" ON "Customers" ("PanNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Loans_LoanNumber" ON "Loans" ("LoanNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_Loans_Status" ON "Loans" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_Loans_CreatedAt" ON "Loans" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_Loans_CustomerId" ON "Loans" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_Loans_CreatedByUserId" ON "Loans" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_Loans_Status_CreatedAt" ON "Loans" ("Status", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_PayoutRules_LoanType" ON "PayoutRules" ("LoanType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_AppSettings_Key" ON "AppSettings" ("Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PasswordResetTokens_TokenHash" ON "PasswordResetTokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_PasswordResetTokens_UserId_IsUsed" ON "PasswordResetTokens" ("UserId", "IsUsed");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_TrackingEntries_LoanId" ON "TrackingEntries" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_TrackingEntries_LoanId_CreatedAt" ON "TrackingEntries" ("LoanId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_LoanReferences_LoanId" ON "LoanReferences" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_DsaPartners_MappedSalesUserId" ON "DsaPartners" ("MappedSalesUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_Teams_LocationId" ON "Teams" ("LocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_Teams_TeamLeadUserId" ON "Teams" ("TeamLeadUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_TeamMembers_TeamId" ON "TeamMembers" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    CREATE INDEX "IX_TeamMembers_UserId" ON "TeamMembers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250101000000_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250101000000_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "ApplicationSource" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredApplicationId" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredCustomerId" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredRequestId" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredOfferStatus" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredOfferJson" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredErrorMessage" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredRejectReason" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredLastWebhookEvent" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredLastWebhookStatus" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    ALTER TABLE "Loans" ADD "IncredLastSyncedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    CREATE TABLE "LoanOffers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "OfferType" character varying(20),
        "LoanAmount" decimal(18,2) NOT NULL,
        "LoanMaxTenure" integer NOT NULL,
        "LoanRate" decimal(5,2) NOT NULL,
        "ProcessingFee" decimal(5,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_LoanOffers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanOffers_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    CREATE INDEX "IX_LoanOffers_LoanId" ON "LoanOffers" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726000000_AddIncredIntegration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260726000000_AddIncredIntegration', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726010000_AddCustomerKycFields') THEN
    ALTER TABLE "Customers" ADD "Gender" character varying(1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726010000_AddCustomerKycFields') THEN
    ALTER TABLE "Customers" ADD "FatherName" character varying(150);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726010000_AddCustomerKycFields') THEN
    ALTER TABLE "Customers" ADD "ResidenceType" character varying(40);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726010000_AddCustomerKycFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260726010000_AddCustomerKycFields', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    ALTER TABLE "DsaPartners" ADD "PartnerType" character varying(20) NOT NULL DEFAULT 'Dsa';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    ALTER TABLE "DsaPartners" ADD "LinkedUserId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    ALTER TABLE "Loans" ADD "DsaId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    ALTER TABLE "Loans" ADD "PartnerId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    ALTER TABLE "Loans" ADD "LocationId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    CREATE INDEX "IX_DsaPartners_LinkedUserId" ON "DsaPartners" ("LinkedUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    CREATE INDEX "IX_Loans_DsaId" ON "Loans" ("DsaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    CREATE INDEX "IX_Loans_PartnerId" ON "Loans" ("PartnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    CREATE INDEX "IX_Loans_LocationId" ON "Loans" ("LocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    ALTER TABLE "DsaPartners" ADD CONSTRAINT "FK_DsaPartners_Users_LinkedUserId" FOREIGN KEY ("LinkedUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    ALTER TABLE "Loans" ADD CONSTRAINT "FK_Loans_DsaPartners_DsaId" FOREIGN KEY ("DsaId") REFERENCES "DsaPartners" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    ALTER TABLE "Loans" ADD CONSTRAINT "FK_Loans_DsaPartners_PartnerId" FOREIGN KEY ("PartnerId") REFERENCES "DsaPartners" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    ALTER TABLE "Loans" ADD CONSTRAINT "FK_Loans_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260728000000_AddDsaPartnerPhase1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260728000000_AddDsaPartnerPhase1', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729000000_AddIncredApplicationIdIndex') THEN
    CREATE INDEX "IX_Loans_IncredApplicationId" ON "Loans" ("IncredApplicationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729000000_AddIncredApplicationIdIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260729000000_AddIncredApplicationIdIndex', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddCustomerMonthlyObligations') THEN
    ALTER TABLE "Customers" ADD "MonthlyObligations" decimal(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddCustomerMonthlyObligations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730000000_AddCustomerMonthlyObligations', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    ALTER TABLE "DsaPartners" ADD "Pan" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    ALTER TABLE "DsaPartners" ADD "OfficeAddress" character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    ALTER TABLE "DsaPartners" ADD "OfficeState" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    ALTER TABLE "DsaPartners" ADD "OfficePin" character varying(10);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    ALTER TABLE "DsaPartners" ADD "OfficeAddressType" character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    ALTER TABLE "DsaPartners" ADD "Category" character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    ALTER TABLE "DsaPartners" ADD "MappedDsaId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    CREATE INDEX "IX_DsaPartners_MappedDsaId" ON "DsaPartners" ("MappedDsaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    ALTER TABLE "DsaPartners" ADD CONSTRAINT "FK_DsaPartners_DsaPartners_MappedDsaId" FOREIGN KEY ("MappedDsaId") REFERENCES "DsaPartners" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    CREATE TABLE "DsaDocuments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DsaPartnerId" integer NOT NULL,
        "DocumentName" character varying(255) NOT NULL,
        "DocumentType" character varying(50) NOT NULL,
        "FilePath" character varying(500) NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "UploadedByUserId" character varying(50) NOT NULL DEFAULT '',
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_DsaDocuments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DsaDocuments_DsaPartners_DsaPartnerId" FOREIGN KEY ("DsaPartnerId") REFERENCES "DsaPartners" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    CREATE INDEX "IX_DsaDocuments_DsaPartnerId" ON "DsaDocuments" ("DsaPartnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730000000_AddDsaPartnerPhase2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730000000_AddDsaPartnerPhase2', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730060000_AddPayoutClaimTypeAndIdempotency') THEN
    ALTER TABLE "PayoutClaims" ADD "ClaimType" character varying(20) NOT NULL DEFAULT 'Sales';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730060000_AddPayoutClaimTypeAndIdempotency') THEN
    UPDATE "PayoutClaims" SET "ClaimType" = 'Sales' WHERE "ClaimType" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730060000_AddPayoutClaimTypeAndIdempotency') THEN
    CREATE UNIQUE INDEX "IX_PayoutClaims_Loan_Claimant_Type_Unique" ON "PayoutClaims" ("LoanId", "ClaimedByUserId", "ClaimType") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730060000_AddPayoutClaimTypeAndIdempotency') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730060000_AddPayoutClaimTypeAndIdempotency', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730120000_AddTicketComments') THEN
    CREATE TABLE "TicketComments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TicketId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "Content" text NOT NULL,
        "Type" character varying(20) NOT NULL DEFAULT 'Comment',
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_TicketComments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TicketComments_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "Tickets" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TicketComments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730120000_AddTicketComments') THEN
    CREATE INDEX "IX_TicketComments_TicketId_CreatedAt" ON "TicketComments" ("TicketId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730120000_AddTicketComments') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730120000_AddTicketComments', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730130000_AddBankMasterPersistence') THEN
    CREATE TABLE "Banks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BankName" character varying(150) NOT NULL,
        "IfscPrefix" character varying(20),
        "EmpCode" character varying(50),
        "Location" character varying(200),
        "RmName" character varying(150),
        "RmMobile" character varying(15),
        "Email" character varying(200),
        "Remarks" character varying(500),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedByUserId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Banks" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730130000_AddBankMasterPersistence') THEN
    CREATE UNIQUE INDEX "IX_Banks_BankName_Unique_Active" ON "Banks" ("BankName") WHERE "IsDeleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730130000_AddBankMasterPersistence') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730130000_AddBankMasterPersistence', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730140000_AddAssignmentLog') THEN
    CREATE TABLE "AssignmentLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityType" character varying(50) NOT NULL,
        "EntityId" integer NOT NULL,
        "FromUserId" integer,
        "FromUserName" character varying(150),
        "ToUserId" integer NOT NULL,
        "ToUserName" character varying(150) NOT NULL,
        "AssignedByUserId" integer NOT NULL,
        "AssignedByName" character varying(150),
        "Notes" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AssignmentLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730140000_AddAssignmentLog') THEN
    CREATE INDEX "IX_AssignmentLogs_EntityType_EntityId" ON "AssignmentLogs" ("EntityType", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730140000_AddAssignmentLog') THEN
    CREATE INDEX "IX_AssignmentLogs_CreatedAt" ON "AssignmentLogs" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730140000_AddAssignmentLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730140000_AddAssignmentLog', '10.0.0');
    END IF;
END $EF$;
COMMIT;

