using LoanMS.Domain.Enums;
using System.ComponentModel.DataAnnotations;

namespace LoanMS.Application.DTOs;

public class CibilBehaviourAnalysisDto
{
    public int RepaymentDisciplineScore { get; set; } // 0-100
    public string? RepaymentDisciplineLevel { get; set; }
    
    public int DelinquencyFrequency { get; set; }
    public string? DelinquencyPattern { get; set; }
    
    public int AccountAgeMonths { get; set; }
    public string? CreditMaturity { get; set; } // New, Young, Mature
    
    public string? LoanClosureBehaviour { get; set; }
    public List<string> AutoGeneratedInsights { get; set; } = new();
}
