using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace LoanMS.Infrastructure.Migrations
{
    /// <summary>
    /// Adds the nine CIBIL/Bureau tables — BureauReports and its eight child
    /// tables — that AppDbContext has always declared (DbSets at
    /// AppDbContext.cs:55-63, full Fluent configuration at :571-672) and that
    /// AppDbContextModelSnapshot.cs has always described, but that NO migration
    /// ever created. The snapshot and the migration history had drifted apart:
    /// the model change was scaffolded into the snapshot without a matching
    /// migration, so a database built purely from "dotnet ef database update"
    /// never had these relations.
    ///
    /// The practical effect was that all seven BureauReports queries in
    /// CibilController (FullReport, Profile, AccountSummary, Accounts,
    /// PaymentHistory, RiskAnalysis, CreditScore) failed against PostgreSQL with
    /// 42P01 undefined_table, which is why the real-ScoreFactors path in
    /// cibil-view.js could never work and the hash-derived breakdown was always
    /// the one that rendered.
    ///
    /// Written as raw SQL rather than scaffolded because the snapshot already
    /// describes these entities: "dotnet ef migrations add" compares against the
    /// snapshot and would therefore emit an EMPTY migration. Raw SQL matches the
    /// convention already used by 20260812000000_AddPerfiosReports and others in
    /// this folder.
    ///
    /// Every statement is IF NOT EXISTS, so this is safe to run against a
    /// database where the tables were already created out-of-band — it becomes a
    /// no-op rather than an error. New, additive tables only. No existing table
    /// is altered and no data is touched.
    ///
    /// Column names, SQL types, nullability and indexes below were generated
    /// directly from AppDbContextModelSnapshot.cs so they cannot drift from the
    /// EF model.
    /// </summary>
    /// <inheritdoc />
    [DbContext(typeof(LoanMS.Infrastructure.Data.AppDbContext))]
    [Migration("20260822000000_AddBureauReportTables")]
    public partial class AddBureauReportTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BureauReports"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""AadhaarNumber"" character varying(20) NOT NULL,
                    ""AccountAge"" integer NOT NULL,
                    ""ActiveAccounts"" integer NOT NULL,
                    ""AnnualIncome"" decimal(18,2) NOT NULL,
                    ""ApprovalProbability"" integer NOT NULL,
                    ""BureauProvider"" character varying(50) NOT NULL,
                    ""BureauRiskScore"" decimal(5,2) NOT NULL,
                    ""CKYCNumber"" character varying(50) NOT NULL,
                    ""ClosedAccounts"" integer NOT NULL,
                    ""ControlNumber"" text NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""CreditMaturity"" character varying(50) NOT NULL,
                    ""CreditScore"" integer NOT NULL,
                    ""CurrentOutstanding"" decimal(18,2) NOT NULL,
                    ""CustomerId"" integer NOT NULL,
                    ""DateOfBirth"" timestamp with time zone NOT NULL,
                    ""DelinquencyFrequency"" integer NOT NULL,
                    ""EligibleForLoan"" boolean NOT NULL,
                    ""EnquiryCount12Months"" integer NOT NULL,
                    ""EnquiryCount24Months"" integer NOT NULL,
                    ""EnquiryCount30Days"" integer NOT NULL,
                    ""EnquiryCount90Days"" integer NOT NULL,
                    ""FullName"" character varying(150) NOT NULL,
                    ""Gender"" character varying(10) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""IsLiveScore"" boolean NOT NULL,
                    ""LatestAccountDate"" timestamp with time zone NOT NULL,
                    ""LendingRecommendation"" character varying(50) NOT NULL,
                    ""LoanClosureBehaviour"" character varying(100) NOT NULL,
                    ""MostRecentEnquiryDate"" timestamp with time zone,
                    ""OccupationType"" character varying(100) NOT NULL,
                    ""OfficeNumber"" text NOT NULL,
                    ""OldestAccountDate"" timestamp with time zone NOT NULL,
                    ""OverdueAmount"" decimal(18,2) NOT NULL,
                    ""PAN"" character varying(10) NOT NULL,
                    ""RepaymentDisciplineScore"" integer NOT NULL,
                    ""RiskCategory"" character varying(50) NOT NULL,
                    ""RiskGrade"" character varying(1) NOT NULL,
                    ""RiskLevel"" character varying(50) NOT NULL,
                    ""ScoreGeneratedDate"" timestamp with time zone NOT NULL,
                    ""SecuredLoanCount"" integer NOT NULL,
                    ""SourceFile"" text NOT NULL,
                    ""TotalAccounts"" integer NOT NULL,
                    ""TotalSanctionAmount"" decimal(18,2) NOT NULL,
                    ""UnsecuredLoanCount"" integer NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_BureauReports"" PRIMARY KEY (""Id"")
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_BureauReports_CustomerId"" ON ""BureauReports"" (""CustomerId"");");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BureauAccounts"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""AccountNumber"" character varying(100) NOT NULL,
                    ""AccountStatus"" character varying(50) NOT NULL,
                    ""ActualLastPayment"" numeric,
                    ""AssetClassification"" text NOT NULL,
                    ""BureauReportId"" integer NOT NULL,
                    ""CashLimit"" numeric,
                    ""ClosedDate"" timestamp with time zone,
                    ""Collateral"" text NOT NULL,
                    ""CollateralType"" text NOT NULL,
                    ""CurrentBalance"" decimal(18,2) NOT NULL,
                    ""DaysOverdue"" integer NOT NULL,
                    ""EMIAmount"" decimal(18,2) NOT NULL,
                    ""HasDelinquency"" boolean NOT NULL,
                    ""InterestRate"" numeric,
                    ""IsSettled"" boolean NOT NULL,
                    ""IsWrittenOff"" boolean NOT NULL,
                    ""LastBankUpdate"" timestamp with time zone,
                    ""LastPaymentDate"" timestamp with time zone,
                    ""LenderName"" character varying(150) NOT NULL,
                    ""LoanType"" character varying(50) NOT NULL,
                    ""OpenDate"" timestamp with time zone NOT NULL,
                    ""Ownership"" character varying(50) NOT NULL,
                    ""PaymentFrequency"" character varying(50) NOT NULL,
                    ""RemainingTenure"" integer NOT NULL,
                    ""RepaymentTenure"" text NOT NULL,
                    ""ReportDate"" timestamp with time zone NOT NULL,
                    ""SanctionAmount"" decimal(18,2) NOT NULL,
                    ""SettlementAmount"" numeric,
                    ""SuitFiledStatus"" text NOT NULL,
                    ""TenureMonths"" integer NOT NULL,
                    ""TotalPaidAmount"" numeric NOT NULL,
                    ""WrittenOffPrincipalAmount"" numeric,
                    ""WrittenOffTotalAmount"" numeric,
                    CONSTRAINT ""PK_BureauAccounts"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BureauAccounts_BureauReports_BureauReportId"" FOREIGN KEY (""BureauReportId"") REFERENCES ""BureauReports"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_BureauAccounts_BureauReportId"" ON ""BureauAccounts"" (""BureauReportId"");");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BureauPaymentHistories"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""BureauAccountId"" integer NOT NULL,
                    ""BureauReportId"" integer NOT NULL,
                    ""DPDStatus"" character varying(10) NOT NULL,
                    ""DaysOverdue"" integer NOT NULL,
                    ""IsMissedPayment"" boolean NOT NULL,
                    ""IsSettlement"" boolean NOT NULL,
                    ""IsWriteOff"" boolean NOT NULL,
                    ""PaidAmount"" decimal(18,2) NOT NULL,
                    ""ReportMonth"" timestamp with time zone NOT NULL,
                    ""ScheduledAmount"" decimal(18,2) NOT NULL,
                    ""Status"" character varying(50) NOT NULL,
                    CONSTRAINT ""PK_BureauPaymentHistories"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BureauPaymentHistories_BureauAccounts_BureauAccountId"" FOREIGN KEY (""BureauAccountId"") REFERENCES ""BureauAccounts"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_BureauPaymentHistories_BureauAccountId_ReportMonth"" ON ""BureauPaymentHistories"" (""BureauAccountId"", ""ReportMonth"");");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BureauEnquiries"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""BureauReportId"" integer NOT NULL,
                    ""EnquiryDate"" timestamp with time zone NOT NULL,
                    ""EnquiryType"" character varying(100) NOT NULL,
                    ""MemberName"" text NOT NULL,
                    ""OwnershipType"" text NOT NULL,
                    ""Purpose"" character varying(100) NOT NULL,
                    ""RequestedAmount"" decimal(18,2) NOT NULL,
                    CONSTRAINT ""PK_BureauEnquiries"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BureauEnquiries_BureauReports_BureauReportId"" FOREIGN KEY (""BureauReportId"") REFERENCES ""BureauReports"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_BureauEnquiries_BureauReportId"" ON ""BureauEnquiries"" (""BureauReportId"");");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BureauAddresses"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""AddressType"" character varying(50) NOT NULL,
                    ""BureauReportId"" integer NOT NULL,
                    ""City"" character varying(100) NOT NULL,
                    ""Country"" character varying(100) NOT NULL,
                    ""DateReported"" timestamp with time zone,
                    ""PostalCode"" character varying(20) NOT NULL,
                    ""State"" character varying(100) NOT NULL,
                    ""Street"" character varying(200) NOT NULL,
                    CONSTRAINT ""PK_BureauAddresses"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BureauAddresses_BureauReports_BureauReportId"" FOREIGN KEY (""BureauReportId"") REFERENCES ""BureauReports"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_BureauAddresses_BureauReportId"" ON ""BureauAddresses"" (""BureauReportId"");");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BureauEmployments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""BureauReportId"" integer NOT NULL,
                    ""EmployerName"" character varying(200) NOT NULL,
                    ""EmploymentEndDate"" timestamp with time zone,
                    ""EmploymentStartDate"" timestamp with time zone,
                    ""EmploymentType"" character varying(50) NOT NULL,
                    ""MonthlyIncome"" decimal(18,2) NOT NULL,
                    ""Occupation"" character varying(100) NOT NULL,
                    CONSTRAINT ""PK_BureauEmployments"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BureauEmployments_BureauReports_BureauReportId"" FOREIGN KEY (""BureauReportId"") REFERENCES ""BureauReports"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_BureauEmployments_BureauReportId"" ON ""BureauEmployments"" (""BureauReportId"");");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BureauMobileNumbers"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""BureauReportId"" integer NOT NULL,
                    ""PhoneNumber"" character varying(20) NOT NULL,
                    CONSTRAINT ""PK_BureauMobileNumbers"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BureauMobileNumbers_BureauReports_BureauReportId"" FOREIGN KEY (""BureauReportId"") REFERENCES ""BureauReports"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_BureauMobileNumbers_BureauReportId"" ON ""BureauMobileNumbers"" (""BureauReportId"");");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BureauEmailAddresses"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""BureauReportId"" integer NOT NULL,
                    ""EmailAddress"" character varying(200) NOT NULL,
                    CONSTRAINT ""PK_BureauEmailAddresses"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BureauEmailAddresses_BureauReports_BureauReportId"" FOREIGN KEY (""BureauReportId"") REFERENCES ""BureauReports"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_BureauEmailAddresses_BureauReportId"" ON ""BureauEmailAddresses"" (""BureauReportId"");");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ScoreFactors"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""BureauReportId"" integer NOT NULL,
                    ""Description"" character varying(500) NOT NULL,
                    ""Factor"" character varying(200) NOT NULL,
                    ""ImpactScore"" integer NOT NULL,
                    ""IsPositive"" boolean NOT NULL,
                    CONSTRAINT ""PK_ScoreFactors"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ScoreFactors_BureauReports_BureauReportId"" FOREIGN KEY (""BureauReportId"") REFERENCES ""BureauReports"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ScoreFactors_BureauReportId"" ON ""ScoreFactors"" (""BureauReportId"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Reverse dependency order; CASCADE covers the FK constraints.
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""ScoreFactors"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""BureauEmailAddresses"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""BureauMobileNumbers"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""BureauEmployments"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""BureauAddresses"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""BureauEnquiries"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""BureauPaymentHistories"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""BureauAccounts"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""BureauReports"" CASCADE;");
        }
    }
}
