// <auto-generated />
// This snapshot enables EF Core to track model state for migrations.
// Re-generate with: dotnet ef migrations add <Name> --project LoanMS.Infrastructure --startup-project LoanMS.API
using LoanMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace LoanMS.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "9.0.5");
        // Full snapshot is generated automatically by dotnet-ef
        // Run: dotnet ef migrations add InitialCreate --project ../LoanMS.Infrastructure --startup-project .
    }
}
